awk -v Cname="   C5" -v Hname="  H51" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="   C5" -v Hname="  H52" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="   C6" -v Hname="  H61" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="   C6" -v Hname="  H62" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C12" -v Hname=" H121" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C12" -v Hname=" H122" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C13" -v Hname=" H131" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C32" -v Hname=" H321" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C32" -v Hname=" H322" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
